JokesSolution/JokesWebsite/Controllers/JokesController.cs
using JokesLib.Interfaces;
using JokesLib.Interfaces.Repositories;
using JokesLib.Models;
using JokesWebsite.Attributes;
using JokesWebsite.Interfaces;
using JokesWebsite.Models;
using JokesWebsite.Models.VM;
using ModelMapping;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LinqDyn;

namespace JokesWebsite.Controllers
{
    public class JokesController : Controller
    {
        private int _itemsPerPage
        {
            get
            {
                int count;
                if (!int.TryParse(ConfigurationManager.AppSettings["JokesPerPage"], out count)) { count = 10; }
                return count;
            }
        }
        private IJokeRepository _repo = null;
        private IModelMapper<Joke, JokeVM> _mapper = null;
        private ICaptcha _captcha = null;
        public int CurrentPage
        {
            get
            {
                int currentPage;
                if (Request["p"] == null || !int.TryParse(Request["p"], out currentPage))
                {
                    currentPage = 1;
                }
                return currentPage;
            }
        }

        public JokesController(IJokeRepository repo, IModelMapper<Joke, JokeVM> mapper, ICaptcha captcha)
        {
            if (repo == null) { throw new ArgumentNullException("repo"); }
            if (mapper == null) { throw new ArgumentNullException("mapper"); }
            if (captcha == null) { throw new ArgumentNullException("captcha"); }
            _repo = repo;
            _mapper = mapper;
            _captcha = captcha;

            if (AuthUser.Instance.IsAuthenticated)
            {
                int totalFavourites;
                int totalRated;
                AuthUser.Instance.RatedJokes = _repo.LoadRated(i => i.AuthUserId == AuthUser.Instance.Id, out totalRated).ToList();
                AuthUser.Instance.FavouriteJokes = _repo.LoadFavourites(u => u.UserId == AuthUser.Instance.Id, out totalFavourites).ToList();
            }
        }
        public ActionResult Index(string sortBy = "PublishDT")
        {
            var model = new List<JokeVM>();
            int totalItems;
            var jokes = _repo.LoadAll(x => x.Status == JokeStatus.Published, out totalItems)
                            .OrderByDescending(sortBy)
                            .Skip(_itemsPerPage * (CurrentPage - 1))
                            .Take(_itemsPerPage)
                            .ToList();
            jokes.ForEach(j => model.Add(_mapper.MapToViewModel(j)));

            ViewBag.SortType = sortBy;
            ViewBag.PagerInfo = new PagerInfo(_itemsPerPage, totalItems, CurrentPage, "?p={0}");
            return View(model);
        }
        public ActionResult Single(Guid id)
        {
            var model = new List<JokeVM>();
            var joke = _repo.Load(id);
            if (joke == null || joke.Status != JokeStatus.Published) { return View("Index", model); }
            model.Add(_mapper.MapToViewModel(joke)); ;
            return View("Index", model);
        }
        public ActionResult Create()
        {
            return View(new JokeVM());
        }
        [HttpPost]
        public ActionResult Create(JokeVM joke)
        {
            if (!_captcha.IsValid()) { ModelState.AddModelError("invalidCaptcha", "გთხოვთ მონიშნოთ რომ არ ხართ ბოტი"); }
            if (!ModelState.IsValid) { return View(); }

            joke.Description = joke.Description.Replace("\n", "<br/>");
            var jokeToAdd = _mapper.MapToEntity(joke);
            _repo.Add(jokeToAdd);
            return View("Completed");
        }
        [AuthorizationRequired]
        public JsonResult Rate(Guid jokeId, int rateValue)
        {
            rateValue = Math.Max(-1, rateValue);
            rateValue = Math.Min(1, rateValue);
            var joke = _repo.Rate(jokeId, rateValue);
            return Json(new
            {
                JokeId = joke.Id,
                TotalVotes = joke.TotalVotes,
                RateValue = joke.RateValue
            }, JsonRequestBehavior.AllowGet);
        }
        [AuthorizationRequired]
        public JsonResult AddToFavourites(Guid jokeId)
        {
            _repo.AddToFavourites(jokeId, AuthUser.Instance.Id);
            return Json(new { isAdded = true, jokeId = jokeId }, JsonRequestBehavior.AllowGet);
        }
        [AuthorizationRequired]
        public JsonResult RemoveFromFavourites(Guid jokeId)
        {
            _repo.DeleteFromFavourites(jokeId, AuthUser.Instance.Id);
            return Json(new { isRemoved = true }, JsonRequestBehavior.AllowGet);
        }
        [AuthorizationRequired]
        public ActionResult Favourites()
        {
            var model = new List<JokeVM>();
            int totalItems;
            var jokes = _repo.LoadFavourites(x => x.UserId == AuthUser.Instance.Id, out totalItems)
                            .Skip(_itemsPerPage * (CurrentPage - 1))
                            .Take(_itemsPerPage)
                            .Where(j => j.Status == JokeStatus.Published)
                            .ToList();
            jokes.ForEach(j => model.Add(_mapper.MapToViewModel(j)));
            ViewBag.PagerInfo = new PagerInfo(_itemsPerPage, totalItems, CurrentPage, "?p={0}");
            return View("Index", model);
        }
    }
}

JokesSolution/JokesWebsite/Views/Jokes/Completed.cshtml
<div class="alert alert-success">
    <p class="center-text">მადლობა. დამატება განხორციელდა წარმატებით.. თქვენი ანეგდოტი ელოდება განხილვას..</p>
</div>
<div class="form-group">
    @Html.ActionLink("ახლის დამატება", "Create", null, new { @class = "btn btn-blue mt10" })
</div>

JokesSolution/JokesWebsite/Views/Jokes/Create.cshtml
@model JokesWebsite.Models.VM.JokeVM
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <section class="navbar navbar-default">
        <div class="navbar-brand d-t w100p">
            <h3 class="t-c">დამატება</h3>
            @Html.TextAreaFor(model => model.Description, new { placeholder = "შეიყვანეთ ტექსტი(წერეთ ქართულად)", data_geokb = "true" })
            <p>
                <input type="submit" class="btn btn-blue mt10" value="დამატება" />
            </p>
            @Html.Partial("_googleCaptcha")
        </div>
    </section>
    <div>
        @Html.ActionLink("მთავარი", "Index")
    </div>
}
<script type="text/javascript" src="~/Scripts/geokb.js"></script>

JokesSolution/JokesWebsite/Views/Jokes/Index.cshtml
@using JokesWebsite.Models.VM
@using JokesLib.Models
@model IEnumerable<JokesWebsite.Models.VM.JokeVM>

@{
    bool _canShowFilter = ViewBag.PagerInfo != null && ((JokesLib.Models.PagerInfo)ViewBag.PagerInfo).TotalItems > 1
                                                    && ViewBag.SortType != null && Model.Count() != 0;

    string addToFavouritesClassName = ViewContext.RouteData.Values["action"].ToString().ToLower() == "favourites" ? "novisible" : "";
    string removeFromFavouritesClassName = addToFavouritesClassName == "novisible" ? "" : "novisible";
}
@functions {
    string GetFavouriteClassName(string jokeId)
    {
        return AuthUser.Instance.FavouriteJokes.FirstOrDefault(j => j.Id.ToString() == jokeId) != null ? "disabled" : "";
    }
}
@using (Html.BeginForm(null, null))
{
    <p>
        @Html.ActionLink("დამატება", "Create") @*, null, new { onclick = "return Joke.CheckIfAuthorized();" })*@
        @if (AuthUser.Instance.IsAuthenticated)
        { @Html.ActionLink("ფავორიტები", "Favourites", "Jokes", null, new { @class = "favourites" }) }
    </p>
    if (_canShowFilter)
    {
        <div class="dropdown">
            <select class="form-control" onchange="Joke.Sort($(this).val())" name="sortBy">
                <option value="new" selected="@(ViewBag.SortType == "PublishDT")">ახალი</option>
                <option value="popular" selected="@(ViewBag.SortType == "RateValue")">პოპულარული</option>
            </select>
        </div>
    }
    <div class="articles-wrapper">
        @foreach (var item in Model)
        {
            <article class="navbar navbar-default" data-jokecontainer="@item.Id">
                <div class="navbar-brand person-container">
                    <div>
                        <span class="close @(removeFromFavouritesClassName)"
                              onclick="Joke.RemoveFromFavourites('@(item.Id)')">&times;</span>
                        <div class="person-title fl-l">
                            <div class="person-title__text">@Html.Raw(item.Description)</div>
                        </div>
                        <span class="pull-right person-vote">
                            <span class="fl-l mr10 @(addToFavouritesClassName) @(GetFavouriteClassName(item.Id.ToString()))"
                                  data-fav-jokeid="@(item.Id)" onclick="Joke.AddToFavourites('@(item.Id)')">
                                <i class="glyphicon glyphicon-star"></i>
                            </span>
                            <span class="fl-l mr10" onclick="Joke.Rate('@(item.Id)', 1)">
                                <i data-thumb-up="@(item.Id)" class="glyphicon glyphicon-thumbs-up pr5 @(item.RateType == RateType.UpVote ? "disabled" : "")"></i>
                                <div class="fl-r" data-jokeid="@item.Id">@item.RateValue</div>
                            </span>
                            <span class="fl-l" onclick="Joke.Rate('@(item.Id)', -1)">
                                <i data-thumb-down="@(item.Id)" class="glyphicon glyphicon-thumbs-down pr5 @(item.RateType == RateType.DownVote ? "disabled" : "")"></i>
                            </span>
                        </span>
                    </div>
                </div>
            </article>
        }
        @if (Model.Count() == 0) { <p class="center-text">ჩანაწერები არ მოიძებნა</p> }
        @if (ViewBag.PagerInfo != null) { @Html.Partial("_pager", (JokesLib.Models.PagerInfo)ViewBag.PagerInfo) }
    </div>
}